### ISSUE TITLE
Improving the user journey

### ISSUE THREAD

**Issue by pabloVoorvaart** [NFTsTv/Broadcastr#10]
Gathered user feedback: 

- I like how it seems simple to use.. couldnt tell fully if it was  recording or it while I was doing a quick uke loop
- When I set the price, I assume it would put them on sale at that price.
- A user does not understand what the app does at all
- I haven't found where to enter the [livepeer.studio](https://livepeer.studio/) URL yet...

(continue in the comments @Mario-SO )

**Comment by Mario-SO** [comment]
- Too much text in the new "create" workflow.

**Comment by pabloVoorvaart** [comment]
continue on notion
