### ISSUE TITLE
Improve branding

### ISSUE THREAD

**Issue by pabloVoorvaart** [NFTsTv/Broadcastr#12]
We need to make a more streamlined branding around the concept of LNFT. Right now we have multiple "names" to refer to the app: nftsAreLive, Live NFTs, NFTs tv etc...

- Think about a better name
- Get a new domain
- Create a short and concise application description
- Create a one line pitch

**Comment by Mario-SO** [comment]
- New name: Broadcastr
    - Chanels are now called Castr
- New domain: broadcastr.xyz

**Comment by Mario-SO** [comment]
Continued on Notion
