### ISSUE TITLE
As a content creator I want to create LNFTs

### ISSUE THREAD

**Issue by pblvrt** [NFTsTv/Broadcastr#2]
We want to allow content creators to deploy LNFTs contracts from within the application.

Contracts can have the following parameters:
- Max number of nfts to be minted ( default would be infinite? )
- Mint price
- Name
- Description
- ....

As well as the contract we need to:
- Create a livepeer channel owned by the user. We need the following information from this livepeer channel: rtmp stream endpoint, streamkey, hls playback url.
- Deploy the html player needs to be deployed to swarm. The swarm .link outputed from this deploy will serve as baseURI for the contract.

Requirements for this task: 
- The user needs to be the one that is paying for the deployment

**Comment by pabloVoorvaart** [comment]
Missing: 

- [ ] Price cannot be bigger than 0 without the contract crashing
- [ ] Implement field to determine LNFT mint limit

@Mario-SO
