### ISSUE TITLE
As a content creator I want to stream to the LNFTs I own

### ISSUE THREAD

**Issue by pblvrt** [NFTsTv/Broadcastr#4]
We want to allow content creators to stream to the LNFTs they own from within the app. 

Task requirements are:
- It should be easy for the content creator to stream to the nft. We should have an "instagram live view", if you click go live button you are streaming directly into the nft.
- Only the content creator should be able to stream to a LNFT if he is the creator or if he is whitelisted on the contract.
- The content creator can stream from both front and back camera.

Edge cases:
- None for now

**Comment by pabloVoorvaart** [comment]
Missing: 

- [ ] Allow only whitelisted ppl to stream to a nft
- [ ] Mobile seems unstable and requires alot of testing
- [ ] Switch camera functionality not working
