### ISSUE TITLE
Update copy for introduction page

### ISSUE THREAD

**Issue by chrishobcroft** [NFTsTv/Broadcastr#49]
Right now, the first thing a user sees when they load up broadcastr.xyz is this:

![Screenshot_20230219-123523_Firefox](https://user-images.githubusercontent.com/2212651/219945441-f0e7b848-044f-46c4-9ad0-4f1957dad89e.png)

Propose this to say:

```
Broadcastr

Welcome to Broadcastr!

Connect your wallet to get started

Connect Wallet
```

Perhaps also even put the logo:

![IMG_20230218_200646_101](https://user-images.githubusercontent.com/2212651/219945597-3c03d8b2-28e9-4da4-bc3a-8d1b9b62a37e.jpg)

**Comment by Mario-SO** [comment]
Done for now, will close this issue but there is still a ton of room for improvement on this.
